import type { Metadata } from "next";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type ChildrenType = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: ChildrenType) => {
  return (
    <html lang="en">
      <body data-theme="light" className="bg-gray-200">{children}</body>
    </html>
  );
};

export default RootLayout;
